// SPDX-FileCopyrightText: 2019 John Irle
// SPDX-License-Identifier: MIT
//
// This file is part of Leadership-quote-generator

export const quotes = [
  "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.@Lao Tzu",
  "Where there is no vision, the people perish.@Proverbs 29:18",
  "I must follow the people. Am I not their leader?@Benjamin Disraeli",
  "You manage things; you lead people.@Rear Admiral Grace Murray Hopper",
  "The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant.@Max DePree",
  "Leadership is the capacity to translate vision into reality.@Warren Bennis",
  "Lead me, follow me, or get out of my way.@General George Patton",
  "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.@Napoleon Bonaparte",
  "You don’t need a title to be a leader.@Multiple Attributions",
  "A leader is one who knows the way, goes the way, and shows the way.@John Maxwell",
  "My own definition of leadership is this: The capacity and the will to rally men and women to a common purpose and the character which inspires confidence.@General Montgomery",
  "Leadership is lifting a person’s vision to high sights, the raising of a person’s performance to a higher standard, the building of a personality beyond its normal limitations.@Peter Drucker",
  "Never doubt that a small group of thoughtful, concerned citizens can change world. Indeed it is the only thing that ever has.@Margaret Mead",
  "The nation will find it very hard to look up to the leaders who are keeping their ears to the ground.@Sir Winston Churchill",
  "The most dangerous leadership myth is that leaders are born-that there is a genetic factor to leadership. That’s nonsense; in fact, the opposite is true. Leaders are made rather than born.@Warren Bennis",
  "To command is to serve, nothing more and nothing less.@Andre Malraux",
  "He who has never learned to obey cannot be a good commander.@Aristotle",
  "Become the kind of leader that people would follow voluntarily; even if you had no title or position.@Brian Tracy",
  "I start with the premise that the function of leadership is to produce more leaders, not more followers.@Ralph Nader",
  "Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes.@Peter Drucker",
  "Anyone can hold the helm when the sea is calm.@Publilius Syrus",
  "A great person attracts great people and knows how to hold them together.@Johann Wolfgang Von Goethe",
  "The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint enough to keep from meddling with them while they do it.@Theodore Roosevelt",
  "Leadership is influence.@John C. Maxwell",
  "You don’t lead by pointing and telling people some place to go. You lead by going to that place and making a case.@Ken Kesey",
  "When I give a minister an order, I leave it to him to find the means to carry it out.@Napoleon Bonaparte",
  "Men make history and not the other way around. In periods where there is no leadership, society stands still. Progress occurs when courageous, skillful leaders seize the opportunity to change things for the better.@Harry S. Truman",
  "People buy into the leader before they buy into the vision.@John Maxwell",
  "So much of what we call management consists in making it difficult for people to work.@Peter Drucker",
  "The art of leadership is saying no, not saying yes. It is very easy to say yes.@Tony Blair",
  "The very essence of leadership is that you have to have a vision. It’s got to be a vision you articulate clearly and forcefully on every occasion. You can’t blow an uncertain trumpet.@Theodore Hesburgh",
  "The key to successful leadership today is influence, not authority.@Kenneth Blanchard",
  "A good general not only sees the way to victory; he also knows when victory is impossible.@Polybius",
  "A great leader’s courage to fulfill his vision comes from passion, not position.@John Maxwell",
  "A leader takes people where they want to go. A great leader takes people where they don’t necessarily want to go, but ought to be.@Rosalynn Carter",
  "The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy; be humble, but not timid; be proud, but not arrogant; have humor, but without folly.@Jim Rohn",
  "Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it’s amazing what they can accomplish.@Sam Walton",
  "A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent.@Douglas MacArthur",
  "A ruler should be slow to punish and swift to reward.@Ovid",
  "No man will make a great leader who wants to do it all himself, or to get all the credit for doing it.@Andrew Carnegie",
  "Leadership is the art of getting someone else to do something you want done because he wants to do it.@General Dwight Eisenhower",
  "The leader has to be practical and a realist yet must talk the language of the visionary and the idealist.@Eric Hoffer",
  "Leaders think and talk about the solutions. Followers think and talk about the problems.@Brian Tracy",
  "A man who wants to lead the orchestra must turn his back on the crowd.@Max Lucado",
  "Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity.@General George Patton",
  "As we look ahead into the next century, leaders will be those who empower others.@Bill Gates",
  "All of the great leaders have had one characteristic in common: it was the willingness to confront unequivocally the major anxiety of their people in their time. This, and not much else, is the essence of leadership.@John Kenneth Galbraith",
  "Do what you feel in your heart to be right–for you’ll be criticized anyway.@Eleanor Roosevelt",
  "Don’t necessarily avoid sharp edges. Occasionally they are necessary to leadership.@Donald Rumsfeld",
  "Education is the mother of leadership.@Wendell Willkie",
  "Effective leadership is putting first things first. Effective management is discipline, carrying it out.@Stephen Covey",
  "Great leaders are almost always great simplifiers, who can cut through argument, debate, and doubt to offer a solution everybody can understand.@General Colin Powell",
  "Great leaders are not defined by the absence of weakness, but rather by the presence of clear strengths.@John Zenger",
  "He who has great power should use it lightly.@Seneca",
  "He who has learned how to obey will know how to command.@Solon",
  "I am reminded how hollow the label of leadership sometimes is and how heroic followership can be.@Warren Bennis",
  "I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody.@Herbert Swope",
  "If one is lucky, a solitary fantasy can totally transform one million realities.@Maya Angelou",
  "If you would not be forgotten, as soon as you are dead and rotten, either write things worth reading, or do things worth the writing.@Benjamin Franklin",
  "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.@John Quincy Adams",
  "In matters of style, swim with the current; in matters of principle, stand like a rock.@Thomas Jefferson",
  "It is absurd that a man should rule others, who cannot rule himself.@Latin Proverb",
  "It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership.@Nelson Mandela",
  "Lead and inspire people. Don’t try to manage and manipulate people. Inventories can be managed but people must be lead.@Ross Perot",
  "Leaders aren’t born, they are made. And they are made just like anything else, through hard work. And that’s the price we’ll have to pay to achieve that goal, or any goal.@Vince Lombardi",
  "Leaders must be close enough to relate to others, but far enough ahead to motivate them.@John C. Maxwell",
  "Leadership and learning are indispensable to each other.@John F. Kennedy",
  "Leadership cannot just go along to get along. Leadership must meet the moral challenge of the day.@Jesse Jackson",
  "Leadership does not always wear the harness of compromise.@Woodrow Wilson",
  "Leadership is a potent combination of strategy and character. But if you must be without one, be without the strategy.@Norman Schwarzkopf",
  "Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership.@Colin Powell",
  "Leadership is the key to 99 percent of all successful efforts.@Erskine Bowles",
  "Leadership is unlocking people’s potential to become better.@Bill Bradley",
  "Management is about arranging and telling. Leadership is about nurturing and enhancing.@Tom Peters",
  "Management is efficiency in climbing the ladder of success; leadership determines whether the ladder is leaning against the right wall.@Stephen Covey",
  "Never give an order that can’t be obeyed.@General Douglas MacArthur",
  "No man is good enough to govern another man without that other’s consent.@Abraham Lincoln",
  "What you do has far greater impact than what you say.@Stephen Covey",
  "Not the cry, but the flight of a wild duck, leads the flock to fly and follow.@Chinese Proverb",
  "One of the tests of leadership is the ability to recognize a problem before it becomes an emergency.@Arnold Glasow",
  "The final test of a leader is that he leaves behind him in other men, the conviction and the will to carry on.@Walter Lippman",
  "The greatest leaders mobilize others by coalescing people around a shared vision.@Ken Blanchard",
  "The growth and development of people is the highest calling of leadership.@Harvey Firestone",
  "To do great things is difficult; but to command great things is more difficult.@Friedrich Nietzsche",
  "To have long term success as a coach or in any position of leadership, you have to be obsessed in some way.@Pat Riley",
  "True leadership lies in guiding others to success. In ensuring that everyone is performing at their best, doing the work they are pledged to do and doing it well.@Bill Owens",
  "We live in a society obsessed with public opinion. But leadership has never been about popularity.@Marco Rubio",
  "Whatever you are, be a good one.@Abraham Lincoln",
  "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.@Eleanor Roosevelt",
  "A competent leader can get efficient service from poor troops, while on the contrary an incapable leader can demoralize the best of troops.@John J Pershing",
  "A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit.@John Maxwell",
  "There are three essentials to leadership: humility, clarity and courage.@Fuchan Yuan",
  "I am endlessly fascinated that playing football is considered a training ground for leadership, but raising children isn’t..@Dee Dee Myers",
  "A cowardly leader is the most dangerous of men.@Stephen King",
  "My responsibility is getting all my players playing for the name on the front of the jersey, not the one on the back.@Unknown",
  "A good plan violently executed now is better than a perfect plan executed next week.@George Patton",
  "The supreme quality of leadership is integrity.@Dwight Eisenhower",
  "You don’t lead by hitting people over the head—that’s assault, not leadership.@Dwight Eisenhower",
  "Earn your leadership every day.@Michael Jordan",
];
